### ISSUE TITLE
AE Conflict of Interest

### ISSUE THREAD

**Issue by jsndyks** [journalovi/2024-Dueck-neighborhood-traces#2]
Having checked through the authors and against the [ACM Guidance on CoIs](https://www.acm.org/publications/policies/conflict-of-interest) we have identified a conflict in relation to @jsndyks work with one of the authors on [Dagstuhl Seminar 23381](https://www.dagstuhl.de/en/seminars/seminar-calendar/seminar-details/23381). <br/>
@jsndyks to withdraw at this stage (before '_responding to the authors with initial submission email_' - no decisions made, no reviewers assigned).<br/>Alternative AE to be appointed.

**Comment by chatchavan** [comment]
Invited a replacement AE with no COI
